// Build the headless agent prompt from the claimed task payload. The driver still
// verifies changed files through git, so the agent's self-report is not trusted.

function summarizePriorRuns(priorRoleOutputs = []) {
  if (!Array.isArray(priorRoleOutputs) || priorRoleOutputs.length === 0) return '';
  // Keep the latest output per role; retries may send repeated role history.
  const byRole = new Map();
  for (const o of priorRoleOutputs) {
    if (o && o.role) byRole.set(o.role, o);
  }
  const lines = [];
  for (const o of byRole.values()) {
    lines.push(`### Role ${o.role} (${o.status || '-'})`);
    if (o.summary) lines.push(o.summary);
    if (Array.isArray(o.findings) && o.findings.length) {
      for (const f of o.findings.slice(0, 8)) lines.push(`- ${f}`);
    }
    lines.push('');
  }
  return lines.join('\n').trim();
}

/**
 * @param {Object} task claimed Claude task
 * @returns {string} prompt for query()
 */
export function buildPrompt(task) {
  const prior = summarizePriorRuns(task.priorRoleOutputs);
  const caps = Array.isArray(task.capabilities) ? task.capabilities.join(', ') : '';
  const fields = Array.isArray(task.requiredFields) && task.requiredFields.length
    ? task.requiredFields.map((f) => (typeof f === 'string' ? f : f?.name)).filter(Boolean).join(', ')
    : '';

  const sections = [
    'You are the PROGRAMMER role in the development pipeline (CODING stage).',
    'You have been assigned one task. Make real, minimal, correct changes in the',
    'current project worktree (cwd) using the available tools.',
    'Do not invent requirements, files, APIs, results, or test outcomes. If a fact',
    'is not available from the task or repository, state that it is unknown.',
    'Do not broaden the scope for optional refactoring or cleanup.',
    '',
    `Project: ${task.project || '-'}    Service: ${task.service || '-'}`,
    `Task: ${task.title || '-'}`,
    caps ? `Capabilities: ${caps}` : '',
    fields ? `Required role fields to cover in the summary: ${fields}` : '',
    '',
    '## Task Description',
    String(task.description || '').trim(),
  ];

  if (prior) {
    sections.push('', '## Previous Role Context', prior);
  }

  sections.push(
    '',
    '## Execution Rules',
    '- Inspect the relevant code before editing.',
    '- Make the smallest change that satisfies the assigned task.',
    '- Add or update relevant tests as code when the task changes behavior.',
    '- If this is a Go project and you use `go`, the environment may require GOWORK=off.',
    '- Do not commit; a later pipeline stage handles git integration.',
    '- Do not claim that tests passed unless you actually ran them and saw the result.',
    // PROGRAMMER-SELF-CHECK-001: раннер всё равно прогоняет проверку сам и вернёт
    // задачу на ремонт при красном — дешевле, чтобы агент увидел это до сдачи.
    '- Before finishing, run the project checks yourself (e.g. `npm test` or'
      + ' `go test ./...` in the service directory) and fix what your change broke.'
      + ' The runner re-runs them after you finish and will send failures back to you.',
    // PROGRAMMER-DELTA-DENYLIST-001: сгенерированные/сборочные артефакты всё равно
    // вырезаются из дельты — не тратить ходы на их правку/регенерацию.
    '- Do not create or edit generated/build artifacts (e.g. *.tsbuildinfo, dist/,'
      + ' build/, node_modules); they are regenerated by tooling and are dropped from your delta.',
    // Кросс-сервисный блокер → честный success=false: оркестратор/аналитик разрулит
    // границу сервиса, вместо того чтобы задача жгла слот в бесконечном requeue.
    `- Keep changes within the assigned service (${task.service || '-'}). If the task truly`
      + ' requires editing another service\'s contract or generated code (e.g. .proto,'
      + ' generated stubs owned elsewhere), return success=false and name the blocker'
      + ' instead of guessing.',
    '',
    '## Required Final Response',
    'The final message must be exactly one JSON object with nothing after it:',
    '{"success": true|false, "summary": "what changed or why it is blocked", "files_changed": ["path1", "path2"]}',
    'Use success=false when the task could not be completed, and explain the blocker in summary.',
    // PROGRAMMER-CROSS-SERVICE-PREFLIGHT-001: если задачу нельзя выполнить в границах
    // своего сервиса без правки контракта/сгенерированного кода ДРУГОГО сервиса —
    // добавь поле "blocked_by_service": "<имя того сервиса>". Оркестратор уводит такую
    // задачу на переразбиение вместо бесконечного requeue (не гадай — назови сервис).
    'If (and only if) you are blocked because the task requires changing another'
      + ' service\'s contract or generated code, additionally set'
      + ' "blocked_by_service": "<that service name>" alongside success=false.',
    // TASK-NEEDS-INPUT-001: спросить человека дешевле, чем угадать и переделать.
    // Раньше единственным выходом было гадать (и сдать не то) либо вернуть голый
    // success=false — задача уходила в requeue и через несколько холостых кругов
    // в BLOCKED, так и не показав человеку ни одного вопроса.
    'If the task is ambiguous in a way you cannot resolve from the repository —'
      + ' a decision only the requester can make (which of two behaviours is wanted,'
      + ' which system is the source of truth, what the expected output should be) —'
      + ' do NOT guess. Return success=false and add'
      + ' "needs_input": {"question": "<one specific question>",'
      + ' "options": ["<option 1>", "<option 2>"], "context": "<what you already established>"}.',
    'Rules for needs_input: ask ONE question that is genuinely blocking; put what you'
      + ' already found out in context so the person does not re-answer the obvious;'
      + ' list options only when the choice is genuinely closed (omit or leave empty'
      + ' otherwise). Do not use it for anything you can determine by reading the code.',
  );

  return sections.filter((s) => s !== undefined && s !== null).join('\n');
}

/**
 * PROGRAMMER-SELF-CHECK-001 — промпт ремонтного захода.
 *
 * Отдаём агенту РОВНО то, что увидел бы человек: команду, код возврата и хвост
 * вывода. Ремонт намеренно узкий — чинить падение, а не продолжать задачу: широкая
 * формулировка на этом шаге заставляет агента переписывать работающий код «заодно».
 *
 * @param {Object} task    исходная задача (нужен контекст, что вообще делали)
 * @param {Object} failure исход упавшей команды из runVerify().failure
 * @param {{attempt:number, maxAttempts:number}} progress
 */
export function buildRepairPrompt(task, failure, { attempt, maxAttempts } = {}) {
  const f = failure || {};
  const why = f.timedOut
    ? `The command timed out (no exit within the limit).`
    : `The command exited with code ${f.exitCode ?? 'unknown'}.`;
  return [
    'You are the PROGRAMMER role. Your previous change in this worktree is complete,',
    'but the project checks are RED, so the work cannot be handed over yet.',
    '',
    `Task: ${task?.title || '-'}    Service: ${task?.service || '-'}`,
    attempt && maxAttempts ? `Repair attempt ${attempt} of ${maxAttempts}.` : '',
    '',
    '## Failing check',
    '```',
    String(f.cmd || ''),
    '```',
    why,
    '',
    '## Output (tail)',
    '```',
    String(f.output || '').trim() || '(no output captured)',
    '```',
    '',
    '## Execution Rules',
    '- Fix the failure. Do not start new work and do not refactor unrelated code.',
    '- If the failure is unrelated to your change and pre-existed, say so in the summary',
    '  instead of rewriting foreign code.',
    '- Re-run the failing command yourself to confirm it is green before finishing.',
    '- Do not commit; a later pipeline stage handles git integration.',
    '',
    '## Required Final Response',
    'The final message must be exactly one JSON object with nothing after it:',
    '{"success": true|false, "summary": "what you fixed", "files_changed": ["path1"]}',
    'Use success=false if you could not make the check green, and explain why in summary.',
  ].filter((s) => s !== undefined && s !== null && s !== '').join('\n');
}

// Extract the final JSON block from the agent output. Returns an object or null.
export function parseAgentJson(text) {
  if (typeof text !== 'string') return null;
  const m = text.match(/\{[\s\S]*\}\s*$/);
  if (!m) return null;
  try {
    return JSON.parse(m[0]);
  } catch {
    return null;
  }
}
