# Редирект с IP на домен
server {
    listen 80;

    server_name 195.98.86.63;

    location / {

        if ($allow_access = 0) {
            return 403;
        }

        proxy_pass  http://server1c;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_hide_header X-Powered-By;
        proxy_hide_header Server;
        proxy_redirect off;
	proxy_buffering off;
	proxy_request_buffering off;
    }

    # Логирование
    access_log /var/log/nginx/server1c.access.log;
    error_log /var/log/nginx/server1c.error.log;

    # Максимальный размер запроса
    client_max_body_size 4G;

    large_client_header_buffers 4 256k;
}

--- RC=0 ---
