user www-data;
worker_processes auto;
worker_cpu_affinity auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;
load_module /etc/nginx/modules-available/ngx_http_geoip2_module.so;


events {
	worker_connections 768;
	# multi_accept on;
}

http {

    # Определяем локальные и частные сети
    geo $allow_ip {
        default 0;
        192.168.1.0/24 1; # Локальная сеть
	172.16.90.0/24 1; # VPN
	173.16.82.0/24 1; # VPN
	217.118.86.0/24 1; # Beeline
	195.98.86.63    1; # Белый IP провайдера
	31.13.72.0/24   1; # Сеть api whatsapp
	77.88.0.0/18    1; # Yandex бот для индексации
	66.249.64.0/20  1; # Google бот для индексации
    }

    # GeoLite2 Country
    geoip2 /etc/nginx/GeoIP/GeoLite2-Country.mmdb {
        $geoip2_country_code country iso_code;
    }

    # Белый список стран
    map $geoip2_country_code $allow_country {
        default 0; # Запрет всем кроме перечисленных внизу
        RU 1; # Разрешен доступ
        BY 1; # Разрешен доступ
	KZ 1; # Разрешен доступ
	UA 0; # Запрещен доступ
	PL 0; # Запрещен доступ
    }


    # Итоговое разрешение
    map "$allow_ip:$allow_country" $allow_access {
	"1:0" 1;   # IP разрешён, страна неважна
	"1:1" 1;   # IP разрешён + страна разрешена
	"0:1" 1;   # IP не в списке, но страна разрешена
	default 0; # Всё остальное блокируем
    }

    #client_max_body_size 100m;
    keepalive_timeout  65;

    # Mapping for WebSocket upgrades
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    upstream httpServer {
        server 192.168.1.140:9090;
    }

    upstream site {
	#server 192.168.1.168:80;    
	server 192.168.1.211:1040;
    }

    upstream chat {
	server 192.168.1.211:1034;
    }

    upstream chatavito {
	server 192.168.1.211:8090;
    }

    upstream beeline {
	server 192.168.1.200:8058;
    }

    upstream server1c {
	server 192.168.1.201:80;    
    }

    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;
    server_tokens off; # Recommended practice is to turn this off

    # server_names_hash_bucket_size 64;
    # server_name_in_redirect off;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;


    include /etc/nginx/conf.d/*.conf;
    #include /etc/nginx/sites-enabled/*;
}



--- RC=0 ---
